import { F } from './constants.js';

// Static world prop catalogue. Collision shapes are in world units.
// c: circle radius; r: rectangle [w, h] before rotation (rot is a multiple of PI/2 for rects).
// mask: which movers it blocks. brk: can be knocked over by vehicles.
const ALL = F.WALK | F.DRIVE | F.SHOT;
const WD = F.WALK | F.DRIVE;

export const PROPS = [
  ['oak', { c: 4, mask: ALL }],
  ['pine', { c: 4, mask: ALL }],
  ['palm', { c: 3, mask: ALL }],
  ['cherry', { c: 4, mask: ALL }],
  ['birch', { c: 3, mask: ALL }],
  ['bush', { c: 6, mask: WD }],
  ['hedge', { r: [16, 16], mask: WD }],
  ['flowers', {}],
  ['lamp', { c: 2, mask: WD, brk: true }],
  ['lantern', { c: 2, mask: WD, brk: true }],
  ['traffic', { c: 2, mask: WD }],
  ['bench', { r: [18, 7], mask: F.WALK, brk: true }],
  ['hydrant', { c: 3, mask: WD, brk: true }],
  ['trash', { c: 4, mask: WD, brk: true }],
  ['mailbox', { c: 3, mask: WD, brk: true }],
  ['busstop', { r: [30, 10], mask: WD }],
  ['fountain', { c: 22, mask: ALL }],
  ['statue', { c: 9, mask: ALL }],
  ['parasol', { c: 2, mask: F.WALK }],
  ['towel', {}],
  ['cafetable', { c: 6, mask: F.WALK, brk: true }],
  ['planter', { r: [14, 14], mask: WD }],
  ['bollard', { c: 2, mask: F.DRIVE }],
  ['phone', { r: [10, 10], mask: WD, brk: true }],
  ['vending', { r: [12, 8], mask: WD }],
  ['newsbox', { r: [7, 6], mask: WD, brk: true }],
  ['foodcart', { r: [24, 12], mask: WD }],
  ['picnic', { r: [20, 16], mask: F.WALK }],
  ['crate', { r: [12, 12], mask: ALL, brk: true }],
  ['barrel', { c: 5, mask: ALL, brk: true }],
  ['dumpster', { r: [22, 12], mask: ALL }],
  ['rock', { c: 8, mask: ALL }],
  ['log', { r: [26, 8], mask: WD }],
  ['campfire', { c: 6, mask: F.DRIVE }],
  ['tent', { r: [24, 20], mask: WD }],
  ['lifeguard', { r: [18, 18], mask: WD }],
  ['boat', { r: [44, 18], mask: ALL }],
  ['buoy', { c: 4, mask: WD }],
  ['slide', { r: [28, 10], mask: WD }],
  ['swing', { r: [30, 12], mask: F.DRIVE }],
  ['bikerack', { r: [20, 6], mask: WD }],
  ['acunit', {}],
  ['watertank', {}],
  ['vent', {}],
  ['solar', {}],
  ['antenna', {}],
  ['roofgarden', {}],
  ['pump', { r: [8, 14], mask: WD }],
  ['cone', { c: 3, mask: F.WALK, brk: true }],
  ['fence', { r: [16, 3], mask: WD }],
  ['railing', { r: [16, 2], mask: WD }],
  ['pallet', { r: [16, 12], mask: F.DRIVE }],
  ['tires', { c: 7, mask: ALL }],
  ['pierpost', { c: 3, mask: WD }],
  ['stall', { r: [30, 18], mask: WD }],
  ['grill', { c: 5, mask: WD }],
  ['sunbed', { r: [22, 9], mask: F.WALK }],
  ['hoop', { r: [6, 6], mask: WD }],
  ['goal', { r: [8, 40], mask: WD }],
  ['volleynet', { r: [4, 60], mask: F.WALK }],
  ['ferris', { c: 30, mask: ALL }],
  ['chimney', {}],
  ['polesign', { c: 3, mask: WD }],
  ['heli', {}],
  ['flagpole', { c: 2, mask: WD }],
  ['well', { c: 9, mask: ALL }],
  ['gazebo', { c: 26, mask: F.DRIVE }],
  ['crane', { r: [24, 24], mask: ALL }],
  ['tank', { c: 30, mask: ALL }],
  ['seesaw', { r: [32, 6], mask: F.DRIVE }],
  ['beachball', {}],
  ['lilypad', {}],
  ['reeds', {}],
  ['stump', { c: 5, mask: WD }],
  ['mushroom', {}],
  ['sign', { c: 2, mask: WD }],
];

export const PROP_ID = Object.fromEntries(PROPS.map(([k], i) => [k, i]));
export const PROP_DEF = PROPS.map(([key, d], id) => ({ id, key, mask: 0, ...d }));
